mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from acces import views

urlpatterns = [
    path("", views.home, name="home"),
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

polls/urls.py
from django.urls import path
from .views import ajouter_question
from django.contrib.auth import views as auth_views

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("all/", views.AllView.as_view(), name="all"),
    path("form/", ajouter_question, name="form"),
    path("stats/", views.StatsView.as_view(), name="stats"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:pk>/frequency/", views.FrequencyView.as_view(), name="frequency"),

]

polls/models.py
import datetime
from django.db.models import Sum
from django.contrib import admin
from django.db import models
from django.utils import timezone
from django import forms
from django.contrib.auth.models import AbstractUser , Group, Permission

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    MAX_LENGTH = 20

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def age(self):
        return timezone.now() - self.pub_date

    def text_excerpt(text, max_length):
        return text[:max_length] + ('...' if len(text) > max_length
                                    else '')

    def get_choices(self):
        resultat = self.choice_set.aggregate(total=Sum('votes'))
        total = resultat['total'] or 0  # Assure-toi que total n'est pas None

        if total == 0:
            # Si total est 0, attribue un pourcentage de 0 pour chaque choix
            return [(c.choice_text, c.votes, 0) for c in self.choice_set.all()]

        # Si total > 0, calcule le pourcentage normalement
        return [(c.choice_text, c.votes, (c.votes / total) * 100) for c in self.choice_set.all()]

    def get_total_choices(cls):
        return cls.objects.aggregate(total=Count('choice'))['total'] or 0

    def get_max_choice(self):
        choices = self.choice_set.all()
        resultat = self.choice_set.aggregate(total=Sum('votes'))
        total = resultat['total']
        max_choice = max(choices, key=lambda c: c.votes / total)
        return (max_choice.choice_text, max_choice.votes / total)





class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    MAX_LENGTH = 20

    def __str__(self):
        return self.choice_text

    def text_excerpt(text, max_length):
        return text[:max_length] + ('...' if len(text) > max_length
                                    else '')

acces/views.py
from django.shortcuts import render

def home(request):
    """Affiche la page d'accueil."""
    return render(request, "acces/home.html")

polls/views.py
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.db.models import Count
from django.db.models import Sum
from django.urls import reverse
from django.views import generic
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib import messages
from .form import QuestionModelForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from .models import Choice, Question
from django.contrib.auth.decorators import login_required

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


def LoginView(request):
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        redirect("polls:index")

class DetailView( generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

class ResultsView( generic.DetailView):
    model = Question
    template_name = "polls/results.html"

class AllView(generic.ListView):
    template_name = 'polls/all.html'
    context_object_name = 'Question'

    def get_queryset(self):
        return Question.objects.all()

class FrequencyView(generic.DetailView):
    model = Question
    context_object_name = 'Question'
    template_name = "polls/frequency.html"

class StatsView(generic.ListView):
    template_name = 'polls/stats.html'
    context_object_name = 'Question'
    model = 'Choice'

    def get_queryset(self):
        return Question.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_choices'] = Question.objects.aggregate(total=Count('choice'))['total'] or 0
        context['total_votes'] = Choice.objects.aggregate(total=Sum('votes'))['total'] or 0
        return context

class QuestionListView( generic.ListView):
    """Affichage de la liste des questions"""
    model = Question
    template_name = "polls/index.html"
    context_object_name = "questions"

@login_required
def ajouter_question(request):
    """Gestion du formulaire d'ajout d'une question avec jusqu'à 5 choix"""
    if request.method == "POST":
        form = QuestionModelForm(request.POST)

        # Vérifier si le formulaire est valide
        if form.is_valid():
            # Créer la question
            question = form.save(commit=False)
            question.pub_date = timezone.now()
            question.save()

            # Récupérer les choix et les enregistrer
            choix1 = form.cleaned_data.get('choix1')
            choix2 = form.cleaned_data.get('choix2')
            choix3 = form.cleaned_data.get('choix3')
            choix4 = form.cleaned_data.get('choix4')
            choix5 = form.cleaned_data.get('choix5')

            # Enregistrer les choix associés à la question
            Choice.objects.create(question=question, choice_text=choix1)
            Choice.objects.create(question=question, choice_text=choix2)
            if choix3:
                Choice.objects.create(question=question, choice_text=choix3)
            if choix4:
                Choice.objects.create(question=question, choice_text=choix4)
            if choix5:
                Choice.objects.create(question=question, choice_text=choix5)

            messages.success(request, "Question et choix ajoutés avec succès !")
            return redirect("polls:index")
        else:
            messages.error(request, "Veuillez remplir tous les champs requis.")

    else:
        form = QuestionModelForm()

    return render(request, "polls/form.html", {"form": form})



def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

acces/templates/acces/home.html
{% extends "base.html" %}  {# Hérite d'un template général, modifiez si besoin #}

{% block content %}
<h2>🔥 Bienvenue sur le site des sondages 🔥 </h2>

<p>Veuillez vous connecter ou accéder en tant qu'invité.</p>

<a href="{% url 'login' %}">🔑 Se connecter ✅ </a> |
<a href="{% url 'polls:index' %}">🏠 Accéder en tant qu'invité</a>

{% endblock %}

polls/templates/polls/all.html
{% extends "base.html" %}
{% load static %}

{% block title %}Toutes les Questions{% endblock %}

{% block content %}
    <h1>Liste de toutes les questions</h1>

    {% if Question %}
        <ul>
        {% for question in Question %}
            <li>id : {{ question.id }} -> <a href="{% url 'polls:frequency' question.id %}">{{ question }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Aucun sondage disponible.</p>
    {% endif %}
    <div class=" btn ">
        <a href="{% url 'polls:index' %}">Retour à l'index</a>
    </div>

    <link rel="stylesheet" href="{% static 'polls/stats.css' %}">
{% endblock %}

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block title %}Repondre a un Sondage{% endblock %}

{% block content %}
    <h1>Repondre au Sondage</h1>

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>

            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}

            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>

        <input type="submit" value="Vote">
    </form>

    <div class="btn">
        <a class="btn" href="{% url 'polls:index' %}">Retour à l'index</a>
    </div>

{% endblock %}

polls/templates/polls/form.html
{% extends "base.html" %}

{% block title %}Ajouter une Question{% endblock %}

{% block content %}

    <h1>Ajouter une question</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Affiche tous les champs de manière structurée -->
        <button type="submit">Créer</button>
    </form>

    <div class="btn">
        <a href="{% url 'polls:index' %}">Voir les questions</a>
    </div>

{% endblock %}

polls/templates/polls/frequency.html
{% extends "base.html" %}
{% load static %}

{% block title %}Statistiques de Fréquence{% endblock %}

{% block content %}
    {% if Question %}
        <h1>Fréquence des Réponses</h1>

        <h3>{{ Question.question_text }}</h3>

        <ul>
            {% for choice in Question.get_choices %}
                <li>
                    Réponse : {{ choice.0 }} / Nombre de fois répondu : {{ choice.1 }} / Pourcentage : {{ choice.2 }} %
                </li>
            {% endfor %}
        </ul>
        <div class=" btn ">
            <a class="btn" href="{% url 'polls:index' %}">Retour à l'index</a>
        </div>


    {% else %}
        <p>Aucune donnée de fréquence disponible.</p>
    {% endif %}
    <link rel="stylesheet" href="{% static 'polls/stats.css' %}">
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block title %}acceuil{% endblock %}

{% block content %}
    <h1>Index (polls)</h1>

    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} </a> ......................{{ question.pub_date }}</li>
        {% endfor %}
        </ul>
        <div>
            <p><a  href="{% url 'polls:form' %}">Formulaire d'ajout question/ réponse</a></p>
            <p><a  href="{% url 'polls:all' %}">ALL</a></p>
            <p><a  href="{% url 'polls:stats' %}">STATS</a></p>
        </div>

    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}
{% load static %}

{% block title %}Résultats{% endblock %}

{% block content %}
    {% if question %}
        <h1>Résultats</h1>

        <h3>{{ question.question_text }}</h3>

        <ul>
            {% for choice in question.choice_set.all %}
                <li>
                    Réponse : {{ choice.choice_text }} / Nombre de fois répondu : {{ choice.votes }} /
                    {{ choice.votes|pluralize }}
                </li>
            {% endfor %}
        </ul>

        <a href="{% url 'polls:detail' question.id %}">Voter à nouveau ?</a>
        <br>

        <div class="btn">
            <a class="btn" href="{% url 'polls:index' %}">Retour à l'index</a>
        </div>

    {% else %}
        <p>Aucune question trouvée.</p>
    {% endif %}

    <link rel="stylesheet" href="{% static 'polls/stats.css' %}">
{% endblock %}

polls/templates/polls/stats.html
{% extends "base.html" %}
{% load static %}

{% block title %}Statistiques des Sondages{% endblock %}

{% block content %}
    {% if Question %}
        <h2>Liste des sondages</h2>
        <ul>
            {% for question in Question %}
                <li>{{ question }}</li>
            {% endfor %}
        </ul>

        <h2>Choix possibles pour toutes les questions au total :</h2>
        <ul>
            <li><p>{{ total_choices }} choix sont possibles toutes questions réunies.</p></li>
        </ul>

        <h2>Nombre total de votes :</h2>
        <ul>
            <li><p>{{ total_votes }} votes ont été effectués.</p></li>
        </ul>
        <div class=" btn ">
            <a href="{% url 'polls:index' %}">Retour a l'index</a>
        </div>

    {% else %}
        <p>Aucun sondage disponible.</p>
    {% endif %}
    <link rel="stylesheet" href="{% static 'polls/stats.css' %}">
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <title>{% block title %}Mon Site{% endblock %}</title>
</head>
<body>
    <header class="header">
        <h1>My Site Test Django</h1>
        {{username}}
        <div class="btnDecoReco">
            {% if user.is_authenticated %}
                <div class="btnadmin">
                    <div class="nameuser"> bonjour : {{user.username}} !</div>
                    <a href="{% url 'logout' %}"> ✅ DéConnection ==> 🔴</a>
                </div>
            {% else %}
                <div class="btnadmin">
                    <div class="nameuser"> bonjour !  </div>
                    <a href="{% url 'login' %}"> 🔴 Connection ==> ✅ </a>
                </div>
            {% endif %}
        </div>
    </header>

    <main>
        {% block content %}
        <p>Contenu principal</p>
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2025 Mon Site. Tous droits réservés a moi meme.</p>
    </footer>
</body>
</html>